title: Kajal Dhawley
description: Data Scientist | ML | Analytics
author: Kajal Dhawley

theme: jekyll-theme-minimal

# Optional: shows a download button in some pages-themes
show_downloads: true

# Add your profile photo path (weâ€™ll add the file in Step 3)
logo: /assets/img/profile.jpg

# Social links (used by some themes/plugins)
email: kajaldhawley@gmail.com
github_username: kajaldhawley

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
